<a href="https://colab.research.google.com/github/radityap99/Data-Mining/blob/main/Generic_Algoritma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np

#f(x) = a +2b +3c +4d -30

n = 6

chromosome = np.random.randint(0,30 ,(n,4))
print("chromosome :", chromosome)
epoch = 0

while epoch < 200 :
  #perhitungan fitness fuction
  objective = abs(30 - chromosome[:,0] - 2*chromosome[:,1] -3*chromosome[:,2] - 4*chromosome[:,3] )
  print("Fitness Object :", objective)

  #Selection Fittes Chromosome
  fitness = 1/(1 + objective)
  print("Fitness :",fitness)

  #Menghitung total fitness fuction
  total = fitness.sum()
  print("Total :",total)

  #Menghitung probabaility setiap chromosome
  prob = fitness/total
  print("Probability :",prob)

  #Menyeleksi menggunakan Roulette Wheel dan menhitung probabilitas kumulatif
  cum_sum = np.cumsum(prob)
  print("Cumulative Sum :", cum_sum)

  #Generating Random Number in the range 0-1
  Ran_nums = np.random.random((chromosome.shape[0]))
  print("Random Numbers :", Ran_nums)

  #mengubah Chromosome Menajdi Matrix
  chromosome_2 = np.zeros((chromosome.shape[0],4))

  for i in range(Ran_nums.shape[0]):
    for j in range(chromosome.shape[0]):
      if Ran_nums[i] < cum_sum[j]:
        chromosome_2[i,:] = chromosome[j,:]
        break

  chromosome = chromosome_2
  print("Chromosome after updation :",chromosome)

  #Crossover
  R = [np.random.random() for i in range(n)]
  print("random Values :",R)

  #Crossover Rate
  pc = 0.25
  flag = Ran_nums < pc
  print("Flagged values :",flag)

  #Menentukan chromosome
  cross_chromosome = chromosome[[(i == True) for i in flag]]
  print("Cross chromosome :",cross_chromosome)
  len_cross_chrom = len(cross_chromosome)

  #Perhitungan cross values
  cross_values = np.random.randint(1,3,len_cross_chrom)
  print("Cross Values :",cross_values)

  cpy_chromosome = np.zeros(cross_chromosome.shape)

  #Copying cromosome values for calculations
  for i in range(cross_chromosome.shape[0]):
    cpy_chromosome[i , :] = cross_chromosome[i , :]

  if len_cross_chrom == 1:
    cross_chromosome = cross_chromosome
  else: 
    for i in range(len_cross_chrom):
      c_val = cross_values[i]
      if i == len_cross_chrom - 1 :
        cross_chromosome[i , c_val:] = cpy_chromosome[0 , c_val:]
      else : 
        cross_chromosome[i , c_val:] = cpy_chromosome[i+1 , c_val:]

  print("Crossovered Chromosome :",cross_chromosome)

  index_chromosome = 0
  index_newchromosome = 0
  for i in flag :
    if i == True :
      chromosome[index_chromosome, :] = cross_chromosome[index_newchromosome, :]
      index_newchromosome = index_newchromosome + 1
    index_chromosome = index_chromosome + 1

  print("New Chromosome:", chromosome)

  #Menghitung total generasi
  a, b = chromosome.shape[0] ,chromosome.shape[1]
  total_gen = a*b 
  print("Total Generations :",total_gen)

  #Mutation rate 
  pm = 0.1
  no_of_mutations = int(np.round(pm * total_gen))
  print("No. of Mutations :" ,no_of_mutations)

  #Menghitung Generation Number
  gen_num = np.random.randint(0, total_gen - 1, no_of_mutations)
  print("Generated random Numbers : ", gen_num)

  #menghasilkan nomer acak yang dapat menggantikan kromosom yang dipilih untuk dimutasi
  Replacing_num = np.random.randint(0,30, no_of_mutations)
  print(" Number to be replace : ", Replacing_num)

  for i in range(no_of_mutations):
    a = gen_num[i]
    row = a//4
    col = a%4
    chromosome[row , col] = Replacing_num[i]

    print(" Chromosome After Mutation :" , chromosome)

    epoch = epoch + 1


chromosome : [[22  7  7 28]
 [27 24  1 22]
 [21 17 17 28]
 [14  1 14  9]
 [ 9 10 28 15]
 [29  5  6  6]]
Fitness Object : [139 136 188  64 143  51]
Fitness : [0.00714286 0.00729927 0.00529101 0.01538462 0.00694444 0.01923077]
Total : 0.06129296156668419
Probability : [0.11653634 0.11908823 0.08632321 0.25100134 0.11329922 0.31375167]
Cumulative Sum : [0.11653634 0.23562456 0.32194777 0.57294911 0.68624833 1.        ]
Random Numbers : [0.75262564 0.66752578 0.1452695  0.88477403 0.52162344 0.50394301]
Chromosome after updation : [[29.  5.  6.  6.]
 [ 9. 10. 28. 15.]
 [27. 24.  1. 22.]
 [29.  5.  6.  6.]
 [14.  1. 14.  9.]
 [14.  1. 14.  9.]]
random Values : [0.12903057759862124, 0.818981796572714, 0.9314652639465393, 0.1376449753270793, 0.9397668458984416, 0.46291718417896577]
Flagged values : [False False  True False False False]
Cross chromosome : [[27. 24.  1. 22.]]
Cross Values : [2]
Crossovered Chromosome : [[27. 24.  1. 22.]]
New Chromosome: [[29.  5.  6.  6.]
 [ 9. 10. 28. 15.]
 [