In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Pizza' 2.0 7200.0]
 ['Burger' 3.0 4800.0]
 ['Kebab' 4.0 5400.0]
 ['Pizza' 6.0 6100.0]
 ['Burger' 5.0 nan]
 ['Kebab' 2.0 5800.0]
 ['Pizza' nan 5200.0]
 ['Burger' 8.0 7900.0]
 ['Kebab' 6.0 8300.0]
 ['Pizza' 5.0 6700.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['Pizza' 2.0 7200.0]
 ['Burger' 3.0 4800.0]
 ['Kebab' 4.0 5400.0]
 ['Pizza' 6.0 6100.0]
 ['Burger' 5.0 6377.777777777777]
 ['Kebab' 2.0 5800.0]
 ['Pizza' 4.555555555555555 5200.0]
 ['Burger' 8.0 7900.0]
 ['Kebab' 6.0 8300.0]
 ['Pizza' 5.0 6700.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[0.0 0.0 1.0 2.0 7200.0]
 [1.0 0.0 0.0 3.0 4800.0]
 [0.0 1.0 0.0 4.0 5400.0]
 [0.0 0.0 1.0 6.0 6100.0]
 [1.0 0.0 0.0 5.0 6377.777777777777]
 [0.0 1.0 0.0 2.0 5800.0]
 [0.0 0.0 1.0 4.555555555555555 5200.0]
 [1.0 0.0 0.0 8.0 7900.0]
 [0.0 1.0 0.0 6.0 8300.0]
 [0.0 0.0 1.0 5.0 6700.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 4.555555555555555 5200.0]
 [1.0 0.0 0.0 5.0 6377.777777777777]
 [0.0 0.0 1.0 2.0 7200.0]
 [0.0 0.0 1.0 6.0 6100.0]
 [1.0 0.0 0.0 3.0 4800.0]
 [1.0 0.0 0.0 8.0 7900.0]
 [0.0 1.0 0.0 6.0 8300.0]
 [0.0 1.0 0.0 2.0 5800.0]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 4.0 5400.0]
 [0.0 0.0 1.0 5.0 6700.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 0.0 1.0 -0.006975631342826131 -1.078125940841243]
 [1.0 0.0 0.0 0.2162445716276038 -0.07013167641635495]
 [0.0 0.0 1.0 -1.2904917984227975 0.6335624327104542]
 [0.0 0.0 1.0 0.7184900283110709 -0.3078661727429792]
 [1.0 0.0 0.0 -0.7882463417393304 -1.4204636155515824]
 [1.0 0.0 0.0 1.722980941678005 1.2326533634535481]
 [0.0 1.0 0.0 0.7184900283110709 1.5749910381638876]
 [0.0 1.0 0.0 -1.2904917984227975 -0.5646194287757338]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 -0.2860008850558633 -0.9069571034860732]
 [0.0 0.0 1.0 0.2162445716276038 0.20564033932252995]]
